### ISSUE TITLE
AC: Injury column in Rosters output

### ISSUE THREAD

**Issue by chaosmical** [chaosmical/web-hockey-league#15]
In the League Manager output, Injuries are in columns 29 and 30, with single digit injuries being in column 30. In AC output, single digit injuries are in column 29. Could you fix that?

e.g.
<pre>
 # player's name         St Inj H  Ps   Ag Qk Pw Fa In Pn Sk Pa PC Ck Sh Ttl
14 Raffi Torres          1-  1  L  LW   7  6  7  5  0  7  7  6  6  6  7  64 LM
14 Raffi Torres          1- 10  L  LW   7  6  7  5  0  7  7  6  6  6  7  64 LM
14 Raffi Torres          1- 1   L  LW   7  6  7  5  0  7  7  6  6  6  7  64 AC
14 Raffi Torres          1- 10  L  LW   7  6  7  5  0  7  7  6  6  6  7  64 AC
</pre>

**Comment by PlatinumCS** [comment]
V1.03.04 gas this correct.

**Comment by chaosmical** [comment]
When can I get this version so I can close off these couple issues? :)
