### ISSUE TITLE
AC: More than 50 retired players

### ISSUE THREAD

**Issue by chaosmical** [chaosmical/web-hockey-league#18]
Have you done anything about one of my earlier requests about being able to have more than 50 retired players? Would likely need to be like 300 to give me room for a few more seasons. Sparrows currently have 206.

**Comment by PlatinumCS** [comment]
V1.03.04 has a cap of 500 retired players.

**Comment by chaosmical** [comment]
It still says (50) though. I didn't actually try importing them though.

**Comment by PlatinumCS** [comment]
Try to import. It SHOULD would. Fingers crossed.

**Comment by chaosmical** [comment]
And you just missed updating the label from 50 to 500 then?
