### ISSUE TITLE
AC: Questions

### ISSUE THREAD

**Issue by chaosmical** [chaosmical/web-hockey-league#21]
1. I think we've discussed this before... Any plans to make a Goalie Injury routine, to replace the one currently used in League Manager?
2. Does AC do promotions/demotions?
3. I processed the Ellis trade in Ac and it went well. I see you have a Pro/Farm designation that determines where the traded player will go, is that correct? So then my question is, do you have anything to handle when a team receives a player and where it's supposed to go already has 25 players?
4. When outputting the Day's files, would you be able to generate this file as well? http://www.webhockeyleague.ca/current/Lines.txt

**Comment by PlatinumCS** [comment]
1. I could add it. Give me some ideas for percentage of likelihood.
2. You can manually promote and demote players. Does it read them from the lineup file and enter them? Not yet, but it will.
3. The OK Button disappears if there isn't enough spots open on the receiving roster. You have to make an even trade.
4. Yes. Eventually. :)
