### ISSUE TITLE
AC: Goalies scoring output

### ISSUE THREAD

**Issue by chaosmical** [chaosmical/web-hockey-league#22]
Is it possible to output the goalies even though they didn't play but were dressed, like in the current scoring files? I would like that.

**Comment by PlatinumCS** [comment]
This is going to be tough. The only way I know if a goalie has played is if he has a Games Played value. I will try and find a way to work around this.

**Comment by chaosmical** [comment]
There has to be a flag or some other value that changes somewhere when a goalie has been dressed as a backup, since the scoring output from HLS2/LM knows that and lists them.
