### ISSUE TITLE
AC: LM: Monitors Output

### ISSUE THREAD

**Issue by chaosmical** [chaosmical/web-hockey-league#23]
In LM4, is there a way to output from the Monitor tools (Scoring/Streaks/Re-rates) like in LM3? I obviously tried double-clicking like I do in LM3 to save a file, bu it doesn't do anything.

I use that daily to output farm ratings changes and add them to the season log (http://www.webhockeyleague.ca/txt/Whl21fprc.txt), and I output the Scoring differences for each 5 game stretch to send to Tyler/Chris for Player of the Week.

**Comment by PlatinumCS** [comment]
New Version is out with the above request completed.
